name: ACEest Fitness Tests

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install stuff
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8
        run: |
          flake8 app.py tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 app.py tests/ --count --exit-zero --max-complexity=10 --max-line-length=127

  test-in-docker:
    needs: linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Build
        run: |
          docker build -t aceest-fitness:latest .

      - name: Run tests
        run: |
          docker run --rm aceest-fitness:latest python -m pytest tests/
